name: 🎉 Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed for progressive mode to work

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        apt install ansible-core
        pip install -Iv 'resolvelib<0.6.0
        ansible-galaxy collection install community.docker