name: 🎉 Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # needed for progressive mode to work

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt install ansible-core
        sudo -H pip install -Iv 'resolvelib<0.6.0'
        ansible-galaxy collection install community.docker

    - name: set ansible config secrets
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
      run: |
        mkdir .ssh
        echo "$DO_SSH_KEY" > .ssh/id_digitalocean
        chmod 600 .ssh/id_digitalocean