name: 🎉 Deploy

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Interactsh docker tag to deploy'
        required: true
        type: string
      push_to_stg:
        description: "test"
        type: boolean
        default: false
        required: true
jobs:
  build:
    name: Ansible Deploy 
    runs-on: ubuntu-latest
    environment: oast
    steps:
    - name: Install dependencies
      run: |
        echo ${{ inputs.tags }}
        echo ${{ inputs.push_to_stg }}
