name: 🎉 Deploy

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Interactsh docker tag to deploy'
        required: false
        type: string
      push_to_stg:
        description: "test"
        type: boolean
        default: false
        required: true
jobs:
  build:
    name: Ansible Deploy 
    runs-on: ubuntu-latest
    environment: oast
    steps:
    - name: echo tag
      run: |
        echo ${{ inputs.tags }}
      if: ${{ inputs.push_to_stg == false && inputs.tags != "" }} 

    - name: echo boolean
      run: |
        echo ${{ inputs.push_to_stg }}
      if: ${{ inputs.push_to_stg  == true }} 